import Head from "next/head";
import Header from "../components/global/Header";
import Carousel from "../components/global/ImageSlider-v2/Carousel";
import PostSlider from "../components/global/PostSlider/PostSlider";
import groq from "groq";
import imageUrlBuilder from "@sanity/image-url";
import { PortableText } from "@portabletext/react";
import client from "../client";
import fetchFirst_X_Posts from "./api/fetchFirst_X_Posts";
import { useRouter } from "next/router";

const images = [
  "https://images.unsplash.com/photo-1506501139174-099022df5260?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1351&q=80",
  "https://images.unsplash.com/photo-1523438097201-512ae7d59c44?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80",
  "https://images.unsplash.com/photo-1513026705753-bc3fffca8bf4?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80",
];

const Home = ({ pageData }) => {
  const {
    title = "Missing title",
    name = "Missing name",
    categories,
    publishedAt = "01.01.2000",
    mainImage,
    body = [],
  } = pageData;

  console.log(pageData)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className="flex justify-center z-0 top-64 h-auto m-auto bg-fixed bg-cover bg-parallax text-center">
        <article className="mt-0 rounded-t-none">
          <div className="flex justify-center">
            <Carousel images={images ? images : undefined} />
          </div>

          <div className="flex justify-center">
            <PostSlider showPageNumber={true} pageData={pageData} />
          </div>

          <div className="max-w-7xl bg-slate-300 mx-auto">
            <h1>Hi, I am a template for NextJS.</h1>
          </div>
        </article>
      </main>
      <footer></footer>
    </div>
  );
};

const query = groq`${fetchFirst_X_Posts(12)}`

export async function getStaticProps() {


  const pageData = await client.fetch(query);

  return {
    props: {
      pageData,
    },
  };
}

export default Home;
