import Head from 'next/head'
import Header from '../components/global/Header'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header/>

      <main className= 'max-w-7xl bg-slate-300 mx-auto'>
        <h1>
          Hi, I am a template for a NextJS blog.
        </h1>
      </main>

      <footer>

      </footer>
    </div>
  )
}
