import Head from 'next/head'
import Header from '../components/global/Header'
import Carousel from '../components/global/ImageSlider-v2/ImageSlider'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      <main className='max-w-7xl bg-slate-300 mx-auto'>
        <h1>
          Hi, I am a template for NextJS.
        </h1>
      </main>
      <div className="w-screen h-80 flex justify-center border-4">
        <Carousel />
       </div>

      <footer>

      </footer>
    </div>
  )
}
